controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

#accueil:
#    path: /accueil
#    controller: App\Controller\AccueilController::index